In [10]:
import numpy as np
import torch
import gymnasium as gym
from utils import Memory

In [2]:
a, b = np.ones(5), np.zeros(5)

In [11]:
torch.tensor(np.vstack((a, b)))

tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [9]:
a.shape

(5,)

In [2]:
env = gym.make("LunarLander-v3", continuous=False, gravity=-10.0,enable_wind=False, wind_power=0.0, turbulence_power=0.0)

In [6]:
state, _ = env.reset()

In [7]:
next_state, reward, _, _, _ = env.step(1)

In [9]:
next_state

array([-0.00549994,  1.3991317 , -0.28551164, -0.27466375,  0.00866638,
        0.11061255,  0.        ,  0.        ], dtype=float32)

In [11]:
memory = Memory(max_size=10)

In [12]:
memory.add(state, 1, reward, next_state, False)

In [13]:
state = next_state
next_state, reward, _, _, _ = env.step(1)
memory.add(state, 1, reward, next_state, False)

In [15]:
batch = memory.sample(2)

In [32]:
c = torch.tensor(np.vstack(batch.state))

In [33]:
c

tensor([[-0.0027,  1.4053, -0.2736, -0.2493,  0.0031,  0.0620,  0.0000,  0.0000],
        [-0.0055,  1.3991, -0.2855, -0.2747,  0.0087,  0.1106,  0.0000,  0.0000]])

In [35]:
c[[0, 1], [0, 1]]

tensor([-0.0027,  1.3991])

In [40]:
np.array(([1, 2]))

array([1, 2])

In [42]:
torch.ones(5)*torch.ones((5, 1))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [43]:
torch.ones((5, 1)).shape

torch.Size([5, 1])